### ISSUE TITLE
automatically setting import_old_db to false

### ISSUE THREAD

**Issue by Newexplorer** [TicklishHoneyBee/nodau#33]
The program automatically sets the value of  import_old_db to false in the configuration file.config/nodau/nodau.conf.
Removing the line import_old_db doesn't work. Setting it to true doesn't work.
And therefore importing the old database doesn't work. The database is of March this year.

nodau -v
nodau 0.3.8 - simple console notetaking program

**Comment by Newexplorer** [comment]
I ran the strace command. I was able to find out that old database had to be located at ~/.local/share/nodau/.
I did that and everything was fine. 
Sorry of the inconvenience.

**Comment by TicklishHoneyBee** [comment]
The import function is for importing data from a 0.2.x database to Nodau 0.3.x. 0.3.0 was released in 2013, so you would need a database that is at least 10 years old in order for the import to occur.

Nodau will check for the existence of a 0.2.x database, import it into a 0.3.x database if it exists, then set import_old_db to false to prevent trying again.

If you're just trying to use a  0.3.x database copied from another system, then it just needs to be moved to ~/.local/share/nodau/nodau.db and it will be used as the current database. (From your second comment, I'm guessing this was the case).
